<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/en_GB.inc                          | 
| Language file of roundcube-pop3fetcher plugin                                                 | 
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti                                    |       
| Licensed under the GNU GPL                                                                                    |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Paolo Moretti <morepaolo@gmail.com>                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['other_accounts'] = 'Autres comptes';
$labels['editaccount'] = 'Editer';
$labels['addaccount'] = 'Ajouter';
$labels['account_email'] = 'Email';
$labels['account_username'] = 'Utilisateur';
$labels['account_password'] = 'Mot de passe';
$labels['account_serveraddress'] = 'Adresse du serveur';
$labels['account_serverport'] = 'Port';
$labels['account_usessl'] = 'Utiliser SSL';
$labels['account_leaveacopy'] = 'Laisser une copie du message sur le serveur';
$labels['account_unableconnect'] = "Connexion au serveur impossible";
$labels['account_provider'] = 'Fournisseur';
$labels['test_connection_on_save'] = 'Tester la connexion en validant';
$labels['account_default_folder'] = 'Dossier de destination';
$labels['pop3fetcher_current_version'] = 'CURRENT VERSION: ';
$labels['pop3fetcher_latest_version'] = 'Derniere version: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher est d&eacute;j&agrave; &agrave; la derni&egrave;re version.';
$labels['pop3fetcher_outdated'] = "Une maj est disponible.<br />T&eacute;l&eacute;charger ";

/* FROM NOW ON: CHECK */
$labels['remoteaccounts'] = 'Compte IMAP';
$labels['pluginname'] = 'Compte IMAP';
$labels['plugindescription'] = 'Autoriser un utilisateur &agrave; acc&eacute;der aux messages stock&eacute;s dans mes dossiers distants.';
$labels['account_dn'] = 'Nom du compte';
$labels['account_id'] = 'ID Utilisateur';
$labels['account_pw'] = 'Mot de passe';
$labels['account_pw_conf'] = 'Confirmation du mot de passe';
$labels['account_provider'] = 'Fournisseur';
$labels['add'] = 'Ajouter';
$labels['back'] = 'Annuler';
$labels['submit'] = 'Valider';
$labels['archivefolder'] = 'Archives';
$labels['remotefolders'] = 'Dossiers sp&eacute;ciaux';
$labels['description'] = 'G&eacute;rer les comptes IMAP suppl&eacute;mentaires';
$labels['dnempty'] = 'Merci de saisir un nom pour ce compte';
$labels['userempty'] = 'Merci de saisir un ID de compte';
$labels['passwordempty'] = 'Merci de saisir un mot de passe';
$labels['passwordnotmatch'] = 'Les mots de passe ne sont pas identiques';
$labels['hostempty'] = 'Merci de saisir l\'adresse du serveur (ex: ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Ce compte existe d&eacute;j&agrave;.';
$labels['connectionfailed'] = 'Impossible de contacter le serveur distant.';

?>
